### ISSUE TITLE
[plugin] where and how do i allow super admin privaleges?

### ISSUE THREAD

**Issue by ScienceDemon** [bitquest/bitquest#197]
while running my spigot server with bitquest, i got this info:
[21:00:43 INFO]: Warning: You haven't designated a super admin. Launch with ADMIN_UUID env variable to set.
How and in what file do I set this with my player uuid?

**Comment by ScienceDemon** [comment]
just asking because it doesn't say how to in the readme.md file under the build instructions

**Comment by theraccoonbear** [comment]
Found this by searching this repo for ADMIN_UUID

https://github.com/bitquest/bitquest/blob/70ef4b379d73f3e5fe94357e22310b7a8ece5084/docker-compose.yml#L8

**Comment by ScienceDemon** [comment]
okay, so what i was doing was i was adding my uuid to /src/main/com/bitquest/bitquest/Bitquest.java
thanks a ton

**Comment by ScienceDemon** [comment]
sorry, i spoke too soon:
Loading libraries, please wait...
[03:28:37 INFO]: Starting minecraft server version 1.12.2
[03:28:37 WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[03:28:37 INFO]: Loading properties
[03:28:37 INFO]: Default game type: CREATIVE
[03:28:38 INFO]: This server is running CraftBukkit version git-Spigot-3d850ec-f46ccd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[03:28:38 INFO]: Server Ping Player Sample Count: 12
[03:28:38 INFO]: Using 4 threads for Netty based IO
[03:28:38 INFO]: Debug logging is disabled
[03:28:38 INFO]: Generating keypair
[03:28:41 INFO]: Starting Minecraft server on *:25565
[03:28:41 INFO]: Using default channel type
[03:28:41 INFO]: Set PluginClassLoader as parallel capable
[03:28:41 INFO]: [HealthBar] Loading HealthBar v1.8.3
[03:28:41 INFO]: [SuperAdmin] Loading SuperAdmin v2.0
[03:28:41 INFO]: [BitQuest] Loading BitQuest v2.0
[03:28:42 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[03:28:42 INFO]: Preparing level "Shut-in-NEET"
[03:28:42 INFO]: -------- World Settings For [Shut-in-NEET] --------
[03:28:42 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[03:28:42 INFO]: Cactus Growth Modifier: 100%
[03:28:42 INFO]: Cane Growth Modifier: 100%
[03:28:42 INFO]: Melon Growth Modifier: 100%
[03:28:42 INFO]: Mushroom Growth Modifier: 100%
[03:28:42 INFO]: Pumpkin Growth Modifier: 100%
[03:28:42 INFO]: Sapling Growth Modifier: 100%
[03:28:42 INFO]: Wheat Growth Modifier: 100%
[03:28:42 INFO]: NetherWart Growth Modifier: 100%
[03:28:42 INFO]: Vine Growth Modifier: 100%
[03:28:42 INFO]: Cocoa Growth Modifier: 100%
[03:28:42 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[03:28:42 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[03:28:42 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[03:28:42 INFO]: Random Lighting Updates: false
[03:28:42 INFO]: Structure Info Saving: true
[03:28:42 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[03:28:42 INFO]: Max TNT Explosions: 100
[03:28:42 INFO]: Mob Spawn Range: 4
[03:28:42 INFO]: View Distance: 10
[03:28:42 INFO]: Experience Merge Radius: 3.0
[03:28:42 INFO]: Zombie Aggressive Towards Villager: true
[03:28:42 INFO]: Item Despawn Rate: 6000
[03:28:42 INFO]: Item Merge Radius: 2.5
[03:28:42 INFO]: Arrow Despawn Rate: 1200
[03:28:42 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[03:28:42 INFO]: Nerfing mobs spawned from spawners: false
[03:28:44 INFO]: -------- World Settings For [Shut-in-NEET_nether] --------
[03:28:44 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[03:28:44 INFO]: Cactus Growth Modifier: 100%
[03:28:44 INFO]: Cane Growth Modifier: 100%
[03:28:44 INFO]: Melon Growth Modifier: 100%
[03:28:44 INFO]: Mushroom Growth Modifier: 100%
[03:28:44 INFO]: Pumpkin Growth Modifier: 100%
[03:28:44 INFO]: Sapling Growth Modifier: 100%
[03:28:44 INFO]: Wheat Growth Modifier: 100%
[03:28:44 INFO]: NetherWart Growth Modifier: 100%
[03:28:44 INFO]: Vine Growth Modifier: 100%
[03:28:44 INFO]: Cocoa Growth Modifier: 100%
[03:28:44 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[03:28:44 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[03:28:44 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[03:28:44 INFO]: Random Lighting Updates: false
[03:28:44 INFO]: Structure Info Saving: true
[03:28:44 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[03:28:44 INFO]: Max TNT Explosions: 100
[03:28:44 INFO]: Mob Spawn Range: 4
[03:28:44 INFO]: View Distance: 10
[03:28:44 INFO]: Experience Merge Radius: 3.0
[03:28:44 INFO]: Zombie Aggressive Towards Villager: true
[03:28:44 INFO]: Item Despawn Rate: 6000
[03:28:44 INFO]: Item Merge Radius: 2.5
[03:28:44 INFO]: Arrow Despawn Rate: 1200
[03:28:44 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[03:28:44 INFO]: Nerfing mobs spawned from spawners: false
[03:28:45 INFO]: -------- World Settings For [Shut-in-NEET_the_end] --------
[03:28:45 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[03:28:45 INFO]: Cactus Growth Modifier: 100%
[03:28:45 INFO]: Cane Growth Modifier: 100%
[03:28:45 INFO]: Melon Growth Modifier: 100%
[03:28:45 INFO]: Mushroom Growth Modifier: 100%
[03:28:45 INFO]: Pumpkin Growth Modifier: 100%
[03:28:45 INFO]: Sapling Growth Modifier: 100%
[03:28:45 INFO]: Wheat Growth Modifier: 100%
[03:28:45 INFO]: NetherWart Growth Modifier: 100%
[03:28:45 INFO]: Vine Growth Modifier: 100%
[03:28:45 INFO]: Cocoa Growth Modifier: 100%
[03:28:45 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[03:28:45 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[03:28:45 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[03:28:45 INFO]: Random Lighting Updates: false
[03:28:45 INFO]: Structure Info Saving: true
[03:28:45 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[03:28:45 INFO]: Max TNT Explosions: 100
[03:28:45 INFO]: Mob Spawn Range: 4
[03:28:45 INFO]: View Distance: 10
[03:28:45 INFO]: Experience Merge Radius: 3.0
[03:28:45 INFO]: Zombie Aggressive Towards Villager: true
[03:28:45 INFO]: Item Despawn Rate: 6000
[03:28:45 INFO]: Item Merge Radius: 2.5
[03:28:45 INFO]: Arrow Despawn Rate: 1200
[03:28:45 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[03:28:45 INFO]: Nerfing mobs spawned from spawners: false
[03:28:45 INFO]: Preparing start region for level 0 (Seed: 10387312)
[03:28:48 INFO]: Preparing spawn area: 0%
[03:28:49 INFO]: Preparing spawn area: 6%
[03:28:50 INFO]: Preparing spawn area: 13%
[03:28:51 INFO]: Preparing spawn area: 21%
[03:28:52 INFO]: Preparing spawn area: 28%
[03:28:53 INFO]: Preparing spawn area: 36%
[03:28:54 INFO]: Preparing spawn area: 43%
[03:28:55 INFO]: Preparing spawn area: 49%
[03:28:56 INFO]: Preparing spawn area: 56%
[03:28:57 INFO]: Preparing spawn area: 62%
[03:28:58 INFO]: Preparing spawn area: 69%
[03:28:59 INFO]: Preparing spawn area: 78%
[03:29:00 INFO]: Preparing spawn area: 87%
[03:29:01 INFO]: Preparing spawn area: 95%
[03:29:01 INFO]: Preparing start region for level 1 (Seed: 10387312)
[03:29:02 INFO]: Preparing spawn area: 7%
[03:29:03 INFO]: Preparing spawn area: 15%
[03:29:05 INFO]: Preparing spawn area: 22%
[03:29:06 INFO]: Preparing spawn area: 31%
[03:29:07 INFO]: Preparing spawn area: 39%
[03:29:08 INFO]: Preparing spawn area: 48%
[03:29:09 INFO]: Preparing spawn area: 56%
[03:29:10 INFO]: Preparing spawn area: 64%
[03:29:11 INFO]: Preparing spawn area: 72%
[03:29:12 INFO]: Preparing spawn area: 80%
[03:29:13 INFO]: Preparing spawn area: 89%
[03:29:14 INFO]: Preparing spawn area: 98%
[03:29:14 INFO]: Preparing start region for level 2 (Seed: 10387312)
[03:29:15 INFO]: Preparing spawn area: 38%
[03:29:16 INFO]: Preparing spawn area: 70%
[03:29:16 INFO]: [HealthBar] Enabling HealthBar v1.8.3
[03:29:16 INFO]: [SuperAdmin] Enabling SuperAdmin v2.0
[03:29:16 INFO]: [BitQuest] Enabling BitQuest v2.0
[03:29:16 INFO]: BitQuest starting
[03:29:16 INFO]: Using the btc/test3 blockchain
[03:29:16 INFO]: Warning: You haven't designated a super admin. Launch with ADMIN_UUID env variable to set.
[03:29:17 INFO]: Unknown command. Type "/help" for help.
[03:29:17 WARN]: java.net.ConnectException: Connection refused
[03:29:17 WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[03:29:17 WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[03:29:17 WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[03:29:17 WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[03:29:17 WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[03:29:17 WARN]: 	at java.net.Socket.connect(Socket.java:589)
[03:29:17 WARN]: 	at java.net.Socket.connect(Socket.java:538)
[03:29:17 WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[03:29:17 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[03:29:17 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[03:29:17 WARN]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
[03:29:17 WARN]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
[03:29:17 WARN]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
[03:29:17 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
[03:29:17 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[03:29:17 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[03:29:17 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
[03:29:17 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
[03:29:17 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
[03:29:17 WARN]: 	at com.bitquest.bitquest.Wallet.getAccountAddress(Wallet.java:124)
[03:29:17 WARN]: 	at com.bitquest.bitquest.Wallet.<init>(Wallet.java:35)
[03:29:17 WARN]: 	at com.bitquest.bitquest.BitQuest.onEnable(BitQuest.java:147)
[03:29:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:29:17 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:29:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[03:29:17 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[03:29:17 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[03:29:17 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[03:29:17 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[03:29:17 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[03:29:17 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[03:29:17 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[03:29:17 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[03:29:17 INFO]: Checking blockchain info...
[03:29:17 INFO]: http://localhost:18332
[03:29:17 INFO]: problem connecting with bitcoin node
[03:29:17 INFO]: java.net.ConnectException: Connection refused
[03:29:17 ERROR]: Error occurred while enabling BitQuest v2.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bitquest.bitquest.BitQuest.killAllVillagers(BitQuest.java:387) ~[?:?]
	at com.bitquest.bitquest.BitQuest.onEnable(BitQuest.java:179) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
[03:29:17 INFO]: Done (35.285s)! For help, type "help" or "?"
[03:29:17 INFO]: Stopping server
[03:29:17 INFO]: [BitQuest] Disabling BitQuest v2.0
[03:29:17 INFO]: [SuperAdmin] Disabling SuperAdmin v2.0
[03:29:17 INFO]: [HealthBar] Disabling HealthBar v1.8.3
[03:29:17 INFO]: HealthBar disabled, all the health bars have been removed.
[03:29:17 INFO]: Saving players
[03:29:17 INFO]: Saving worlds
[03:29:17 INFO]: Saving chunks for level 'world'/overworld
[03:29:17 INFO]: Saving chunks for level 'world_nether'/the_nether
[03:29:17 INFO]: Saving chunks for level 'world_the_end'/the_end

**Comment by ScienceDemon** [comment]
i just took the time to realise: I'm on an ARM architecture of raspbian linux so... this plugin doesn't work on raspberry pi 3.

**Comment by juanj** [comment]
I don't see why it would not work in a pi3. If you can run java, you can run BitQuest.
I think is more a config problem.
