### ISSUE TITLE
i'm still running into problems with the plugin

### ISSUE THREAD

**Issue by ScienceDemon** [bitquest/bitquest#198]
I have the built release branch loaded, but it keeps crashing every time it finishes loading the server
I have multiverse core, multiverse portals and health bar as my other plugins
my specs are: motherboard: raspberry pi 3 w/ clear case
my OS is the full version of Raspbian (Debian edit for raspberry pi)
console log is as follows:
Loading libraries, please wait...
[18:44:58 INFO]: Starting minecraft server version 1.12.2
[18:44:58 WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[18:44:58 INFO]: Loading properties
[18:44:58 INFO]: Default game type: CREATIVE
[18:44:59 INFO]: This server is running CraftBukkit version git-Spigot-3d850ec-f46ccd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:44:59 INFO]: Server Ping Player Sample Count: 12
[18:44:59 INFO]: Using 4 threads for Netty based IO
[18:44:59 INFO]: Debug logging is disabled
[18:44:59 INFO]: Generating keypair
[18:45:00 INFO]: Starting Minecraft server on *:25565
[18:45:00 INFO]: Using default channel type
[18:45:01 INFO]: Set PluginClassLoader as parallel capable
[18:45:02 INFO]: [HealthBar] Loading HealthBar v1.8.3
[18:45:02 INFO]: [BitQuest] Loading BitQuest v2.0
[18:45:02 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5.0-b727
[18:45:02 INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5.0-b751
[18:45:02 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[18:45:02 INFO]: Preparing level "Shut-in-NEET"
[18:45:02 INFO]: -------- World Settings For [Shut-in-NEET] --------
[18:45:02 INFO]: Cactus Growth Modifier: 100%
[18:45:02 INFO]: Cane Growth Modifier: 100%
[18:45:02 INFO]: Melon Growth Modifier: 100%
[18:45:02 INFO]: Mushroom Growth Modifier: 100%
[18:45:02 INFO]: Pumpkin Growth Modifier: 100%
[18:45:02 INFO]: Sapling Growth Modifier: 100%
[18:45:02 INFO]: Wheat Growth Modifier: 100%
[18:45:02 INFO]: NetherWart Growth Modifier: 100%
[18:45:02 INFO]: Vine Growth Modifier: 100%
[18:45:02 INFO]: Cocoa Growth Modifier: 100%
[18:45:02 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:45:02 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:45:02 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:45:02 INFO]: Random Lighting Updates: false
[18:45:02 INFO]: Structure Info Saving: true
[18:45:02 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:45:02 INFO]: Max TNT Explosions: 100
[18:45:02 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:45:02 INFO]: Mob Spawn Range: 4
[18:45:02 INFO]: Arrow Despawn Rate: 1200
[18:45:02 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:45:02 INFO]: View Distance: 10
[18:45:02 INFO]: Experience Merge Radius: 3.0
[18:45:02 INFO]: Zombie Aggressive Towards Villager: true
[18:45:02 INFO]: Item Despawn Rate: 6000
[18:45:02 INFO]: Item Merge Radius: 2.5
[18:45:02 INFO]: Nerfing mobs spawned from spawners: false
[18:45:05 INFO]: -------- World Settings For [Shut-in-NEET_nether] --------
[18:45:05 INFO]: Cactus Growth Modifier: 100%
[18:45:05 INFO]: Cane Growth Modifier: 100%
[18:45:05 INFO]: Melon Growth Modifier: 100%
[18:45:05 INFO]: Mushroom Growth Modifier: 100%
[18:45:05 INFO]: Pumpkin Growth Modifier: 100%
[18:45:05 INFO]: Sapling Growth Modifier: 100%
[18:45:05 INFO]: Wheat Growth Modifier: 100%
[18:45:05 INFO]: NetherWart Growth Modifier: 100%
[18:45:05 INFO]: Vine Growth Modifier: 100%
[18:45:05 INFO]: Cocoa Growth Modifier: 100%
[18:45:05 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:45:05 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:45:05 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:45:05 INFO]: Random Lighting Updates: false
[18:45:05 INFO]: Structure Info Saving: true
[18:45:05 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:45:05 INFO]: Max TNT Explosions: 100
[18:45:05 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:45:05 INFO]: Mob Spawn Range: 4
[18:45:05 INFO]: Arrow Despawn Rate: 1200
[18:45:05 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:45:05 INFO]: View Distance: 10
[18:45:05 INFO]: Experience Merge Radius: 3.0
[18:45:05 INFO]: Zombie Aggressive Towards Villager: true
[18:45:05 INFO]: Item Despawn Rate: 6000
[18:45:05 INFO]: Item Merge Radius: 2.5
[18:45:05 INFO]: Nerfing mobs spawned from spawners: false
[18:45:05 INFO]: -------- World Settings For [Shut-in-NEET_the_end] --------
[18:45:05 INFO]: Cactus Growth Modifier: 100%
[18:45:05 INFO]: Cane Growth Modifier: 100%
[18:45:05 INFO]: Melon Growth Modifier: 100%
[18:45:05 INFO]: Mushroom Growth Modifier: 100%
[18:45:05 INFO]: Pumpkin Growth Modifier: 100%
[18:45:05 INFO]: Sapling Growth Modifier: 100%
[18:45:05 INFO]: Wheat Growth Modifier: 100%
[18:45:05 INFO]: NetherWart Growth Modifier: 100%
[18:45:05 INFO]: Vine Growth Modifier: 100%
[18:45:05 INFO]: Cocoa Growth Modifier: 100%
[18:45:05 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:45:05 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:45:05 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:45:05 INFO]: Random Lighting Updates: false
[18:45:05 INFO]: Structure Info Saving: true
[18:45:05 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:45:05 INFO]: Max TNT Explosions: 100
[18:45:05 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:45:05 INFO]: Mob Spawn Range: 4
[18:45:05 INFO]: Arrow Despawn Rate: 1200
[18:45:05 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:45:05 INFO]: View Distance: 10
[18:45:05 INFO]: Experience Merge Radius: 3.0
[18:45:05 INFO]: Zombie Aggressive Towards Villager: true
[18:45:05 INFO]: Item Despawn Rate: 6000
[18:45:05 INFO]: Item Merge Radius: 2.5
[18:45:05 INFO]: Nerfing mobs spawned from spawners: false
[18:45:05 INFO]: Preparing start region for level 0 (Seed: 10387312)
[18:45:08 INFO]: Preparing spawn area: 0%
[18:45:09 INFO]: Preparing spawn area: 4%
[18:45:10 INFO]: Preparing spawn area: 11%
[18:45:11 INFO]: Preparing spawn area: 18%
[18:45:12 INFO]: Preparing spawn area: 25%
[18:45:13 INFO]: Preparing spawn area: 33%
[18:45:14 INFO]: Preparing spawn area: 40%
[18:45:15 INFO]: Preparing spawn area: 46%
[18:45:16 INFO]: Preparing spawn area: 52%
[18:45:17 INFO]: Preparing spawn area: 58%
[18:45:18 INFO]: Preparing spawn area: 65%
[18:45:19 INFO]: Preparing spawn area: 72%
[18:45:20 INFO]: Preparing spawn area: 80%
[18:45:21 INFO]: Preparing spawn area: 88%
[18:45:22 INFO]: Preparing spawn area: 96%
[18:45:23 INFO]: Preparing start region for level 1 (Seed: 10387312)
[18:45:24 INFO]: Preparing spawn area: 6%
[18:45:25 INFO]: Preparing spawn area: 14%
[18:45:26 INFO]: Preparing spawn area: 21%
[18:45:27 INFO]: Preparing spawn area: 29%
[18:45:28 INFO]: Preparing spawn area: 38%
[18:45:29 INFO]: Preparing spawn area: 46%
[18:45:30 INFO]: Preparing spawn area: 54%
[18:45:31 INFO]: Preparing spawn area: 61%
[18:45:32 INFO]: Preparing spawn area: 69%
[18:45:33 INFO]: Preparing spawn area: 77%
[18:45:34 INFO]: Preparing spawn area: 83%
[18:45:35 INFO]: Preparing spawn area: 92%
[18:45:36 INFO]: Preparing start region for level 2 (Seed: 10387312)
[18:45:37 INFO]: Preparing spawn area: 46%
[18:45:38 INFO]: [HealthBar] Enabling HealthBar v1.8.3
[18:45:38 INFO]: [BitQuest] Enabling BitQuest v2.0
[18:45:38 INFO]: BitQuest starting
[18:45:38 INFO]: Using the btc/test3 blockchain
[18:45:38 INFO]: Warning: You haven't designated a super admin. Launch with ADMIN_UUID env variable to set.
[18:45:39 INFO]: Unknown command. Type "/help" for help.
[18:45:39 WARN]: java.net.ConnectException: Connection refused
[18:45:39 WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[18:45:39 WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[18:45:39 WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[18:45:39 WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[18:45:39 WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[18:45:39 WARN]: 	at java.net.Socket.connect(Socket.java:589)
[18:45:39 WARN]: 	at java.net.Socket.connect(Socket.java:538)
[18:45:39 WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[18:45:39 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[18:45:39 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[18:45:39 WARN]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
[18:45:39 WARN]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
[18:45:39 WARN]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
[18:45:39 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
[18:45:39 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[18:45:39 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[18:45:39 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
[18:45:39 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
[18:45:39 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
[18:45:39 WARN]: 	at com.bitquest.bitquest.Wallet.getAccountAddress(Wallet.java:124)
[18:45:39 WARN]: 	at com.bitquest.bitquest.Wallet.<init>(Wallet.java:35)
[18:45:39 WARN]: 	at com.bitquest.bitquest.BitQuest.onEnable(BitQuest.java:147)
[18:45:39 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:45:39 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[18:45:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[18:45:39 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[18:45:39 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[18:45:39 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[18:45:39 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[18:45:39 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[18:45:39 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[18:45:39 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[18:45:39 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:45:39 INFO]: Checking blockchain info...
[18:45:39 INFO]: http://localhost:18332
[18:45:39 INFO]: problem connecting with bitcoin node
[18:45:39 INFO]: java.net.ConnectException: Connection refused
[18:45:39 ERROR]: Error occurred while enabling BitQuest v2.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bitquest.bitquest.BitQuest.killAllVillagers(BitQuest.java:387) ~[?:?]
	at com.bitquest.bitquest.BitQuest.onEnable(BitQuest.java:179) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
[18:45:39 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5.0-b727
[18:45:40 INFO]: -------- World Settings For [factions1] --------
[18:45:40 INFO]: Cactus Growth Modifier: 100%
[18:45:40 INFO]: Cane Growth Modifier: 100%
[18:45:40 INFO]: Melon Growth Modifier: 100%
[18:45:40 INFO]: Mushroom Growth Modifier: 100%
[18:45:40 INFO]: Pumpkin Growth Modifier: 100%
[18:45:40 INFO]: Sapling Growth Modifier: 100%
[18:45:40 INFO]: Wheat Growth Modifier: 100%
[18:45:40 INFO]: NetherWart Growth Modifier: 100%
[18:45:40 INFO]: Vine Growth Modifier: 100%
[18:45:40 INFO]: Cocoa Growth Modifier: 100%
[18:45:40 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:45:40 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:45:40 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:45:40 INFO]: Random Lighting Updates: false
[18:45:40 INFO]: Structure Info Saving: true
[18:45:40 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:45:40 INFO]: Max TNT Explosions: 100
[18:45:40 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:45:40 INFO]: Mob Spawn Range: 4
[18:45:40 INFO]: Arrow Despawn Rate: 1200
[18:45:40 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:45:40 INFO]: View Distance: 10
[18:45:40 INFO]: Experience Merge Radius: 3.0
[18:45:40 INFO]: Zombie Aggressive Towards Villager: true
[18:45:40 INFO]: Item Despawn Rate: 6000
[18:45:40 INFO]: Item Merge Radius: 2.5
[18:45:40 INFO]: Nerfing mobs spawned from spawners: false
[18:45:40 INFO]: Preparing start region for level 3 (Seed: -6897589223037046670)
[18:45:43 INFO]: Preparing spawn area for factions1, 0%
[18:45:44 INFO]: Preparing spawn area for factions1, 8%
[18:45:45 INFO]: Preparing spawn area for factions1, 12%
[18:45:46 INFO]: Preparing spawn area for factions1, 16%
[18:45:47 INFO]: Preparing spawn area for factions1, 24%
[18:45:48 INFO]: Preparing spawn area for factions1, 32%
[18:45:49 INFO]: Preparing spawn area for factions1, 40%
[18:45:50 INFO]: Preparing spawn area for factions1, 44%
[18:45:51 INFO]: Preparing spawn area for factions1, 52%
[18:45:52 INFO]: Preparing spawn area for factions1, 57%
[18:45:53 INFO]: Preparing spawn area for factions1, 65%
[18:45:54 INFO]: Preparing spawn area for factions1, 73%
[18:45:55 INFO]: Preparing spawn area for factions1, 77%
[18:45:56 INFO]: Preparing spawn area for factions1, 89%
[18:45:57 INFO]: Preparing spawn area for factions1, 97%
[18:45:58 INFO]: [Multiverse-Core] 4 - World(s) loaded.
[18:45:59 INFO]: [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
[18:45:59 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5.0-b751
[18:45:59 INFO]: [Multiverse-Portals] - Version 2.5.0-b751 Enabled - By Rigby and fernferret
[18:45:59 INFO]: [MVPLogging] 0 - Portals(s) loaded
[18:46:00 INFO]: Done (58.182s)! For help, type "help" or "?"
[18:46:00 INFO]: Stopping server
[18:46:00 INFO]: [Multiverse-Portals] Disabling Multiverse-Portals v2.5.0-b751
[18:46:00 INFO]: [Multiverse-Core] Disabling Multiverse-Core v2.5.0-b727
[18:46:00 INFO]: [BitQuest] Disabling BitQuest v2.0
[18:46:00 INFO]: [HealthBar] Disabling HealthBar v1.8.3
[18:46:00 INFO]: HealthBar disabled, all the health bars have been removed.
[18:46:00 INFO]: Saving players
[18:46:00 INFO]: Saving worlds
[18:46:00 INFO]: Saving chunks for level 'Shut-in-NEET'/overworld
[18:46:00 INFO]: Saving chunks for level 'Shut-in-NEET_nether'/the_nether
[18:46:00 INFO]: Saving chunks for level 'Shut-in-NEET_the_end'/the_end
[18:46:00 INFO]: Saving chunks for level 'factions1'/overworld
>end log, please help.

**Comment by Chocoman12** [comment]
Looak at your ports, they may be close, sorry for my English, i'm french so...

**Comment by juanj** [comment]
I can see two things form your log
1. `[18:45:39 INFO]: problem connecting with bitcoin node` -> BitQuest uses a full Bitcoin node to check balances and generate Bitcoin addresses. It it is failing to get an address for the player when it connects:
 `[18:45:39 WARN]: java.net.ConnectException: Connection refused`
`[18:45:39 WARN]: at com.bitquest.bitquest.Wallet.getAccountAddress(Wallet.java:124)`
2. When the server starts it tries to kill all villagers but it is failing to get a reference to the world. (Maybe because of the previous error? I'm not sure).
`java.lang.NullPointerException: null
at com.bitquest.bitquest.BitQuest.killAllVillagers(BitQuest.java:387) ~[?:?]`

**Comment by ScienceDemon** [comment]
@Chocoman12 the port is obviously wrong as well as the 'localhost' address. my os is on a 16 Gigabyte microSD card, so i can't run a bitcoin node. as for the ram, in pi3, there is ONLY a 1gb ddr2 chip on it.
@juanj
thanks:
>[18:45:39 WARN]: java.net.ConnectException: Connection refused
>[18:45:39 WARN]: at com.bitquest.bitquest.Wallet.getAccountAddress(Wallet.java:124)
was actually because the default node address in the release branch are localhost:18332

**Comment by ScienceDemon** [comment]
i get why whoever made it localhost:18332 did it: they didn't want to be tracked by people
