### ISSUE TITLE
COMPILE ERROR & MULTIPLE ERRORS

### ISSUE THREAD

**Issue by donthamon** [bitquest/bitquest#292]
web_1    |  * Serving Flask app "app.py"
web_1    |  * Environment: production
web_1    |    WARNING: This is a development server. Do not use it in a production deployment.
web_1    |    Use a production WSGI server instead.
web_1    |  * Debug mode: off
web_1    | Usage: flask run [OPTIONS]
web_1    |
web_1    | Error: Could not import "app".
minecraftcompose_web_1 exited with code 2

**Comment by donthamon** [comment]
[16:37:30 INFO]: Checking that POSTGRES_PORT_5432_TCP_PORT envoronment variable exists...

[16:37:30 INFO]: Please set the POSTGRES_PORT_5432_TCP_PORT environment variable

[16:37:30 WARN]: JDBC URL invalid port number: null

[16:37:30 WARN]: java.sql.SQLException: No suitable driver found for jdbc:postgresql://null:null/null?ssl=true&sslmode=require

[16:37:30 WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:689)

[16:37:30 WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:247)

[16:37:30 WARN]: at com.bitquest.bitquest.BitQuest.onEnable(BitQuest.java:142)

[16:37:30 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)

[16:37:30 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)

[16:37:30 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)

[16:37:30 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)

[16:37:30 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)

[16:37:30 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)

[16:37:30 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)

[16:37:30 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)

[16:37:30 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)

[16:37:30 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)

[16:37:30 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by donthamon** [comment]
#22 15.09 [INFO] 4 warnings
#22 15.09 [INFO] -------------------------------------------------------------
#22 15.09 [INFO] -------------------------------------------------------------
#22 15.09 [ERROR] COMPILATION ERROR :
#22 15.09 [INFO] -------------------------------------------------------------
#22 15.09 [ERROR] /bitquest/src/main/java/com/bitquest/bitquest/Wallet.java:[15,22] package javax.xml.bind does not exist
#22 15.09 [ERROR] /bitquest/src/main/java/com/bitquest/bitquest/Wallet.java:[125,24] cannot find symbol
#22 15.09   symbol:   variable DatatypeConverter
#22 15.09   location: class com.bitquest.bitquest.Wallet
#22 15.09 [INFO] 2 errors
#22 15.09 [INFO] -------------------------------------------------------------
#22 15.09 [INFO] ------------------------------------------------------------------------
#22 15.09 [INFO] BUILD FAILURE
#22 15.09 [INFO] ------------------------------------------------------------------------
#22 15.09 [INFO] Total time:  12.904 s
#22 15.09 [INFO] Finished at: 2021-01-27T00:56:21Z
#22 15.09 [INFO] ------------------------------------------------------------------------
#22 15.10 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project BitQuest: Compilation failure: Compilation failure:
#22 15.10 [ERROR] /bitquest/src/main/java/com/bitquest/bitquest/Wallet.java:[15,22] package javax.xml.bind does not exist
#22 15.10 [ERROR] /bitquest/src/main/java/com/bitquest/bitquest/Wallet.java:[125,24] cannot find symbol
#22 15.10 [ERROR]   symbol:   variable DatatypeConverter
#22 15.10 [ERROR]   location: class com.bitquest.bitquest.Wallet
#22 15.10 [ERROR] -> [Help 1]
#22 15.10 [ERROR]
#22 15.10 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#22 15.10 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#22 15.10 [ERROR]
#22 15.10 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#22 15.10 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
