### ISSUE TITLE
The server is shutting down due to a plugin error because the plugin is not connecting to something

### ISSUE THREAD

**Issue by PillagerMC** [bitquest/bitquest#305]
When the server starts with the plugin, it crashes after loading the world. It connects to localhost: 44555 and exits
```[20:27:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:28:04] [main/INFO]: Reloading ResourceManager: Default, bukkit
[20:28:08] [Worker-Main-4/INFO]: Loaded 7 recipes
[20:28:15] [Server thread/INFO]: Starting minecraft server version 1.16.5
[20:28:15] [Server thread/INFO]: Loading properties
[20:28:20] [Server thread/INFO]: This server is running CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[20:28:22] [Server thread/INFO]: Debug logging is disabled
[20:28:22] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:28:23] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:28:23] [Server thread/INFO]: Default game type: SURVIVAL
[20:28:23] [Server thread/INFO]: Generating keypair
[20:28:23] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:28:24] [Server thread/INFO]: Using default channel type
[20:28:33] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[20:28:42] [Server thread/WARN]: Legacy plugin BitQuest v2.0 does not specify an api-version.
[20:28:42] [Server thread/INFO]: [BitQuest] Loading BitQuest v2.0
[20:28:42] [Server thread/INFO]: Preparing level "world"
[20:28:42] [Server thread/INFO]: -------- World Settings For [world] --------
[20:28:42] [Server thread/INFO]: View Distance: 10
[20:28:42] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:28:42] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:28:42] [Server thread/INFO]: Item Despawn Rate: 6000
[20:28:42] [Server thread/INFO]: Item Merge Radius: 2.5
[20:28:42] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[20:28:42] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:28:42] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Carrot Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Potato Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Vine Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Kelp Growth Modifier: 100%
[20:28:42] [Server thread/INFO]: Mob Spawn Range: 6
[20:28:42] [Server thread/INFO]: Max TNT Explosions: 100
[20:28:42] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:28:42] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[20:28:42] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:28:42] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:28:42] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:28:42] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[20:28:43] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[20:28:43] [Server thread/INFO]: View Distance: 10
[20:28:43] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:28:43] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:28:43] [Server thread/INFO]: Item Despawn Rate: 6000
[20:28:43] [Server thread/INFO]: Item Merge Radius: 2.5
[20:28:43] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[20:28:43] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:28:43] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Carrot Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Potato Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Vine Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Kelp Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Mob Spawn Range: 6
[20:28:43] [Server thread/INFO]: Max TNT Explosions: 100
[20:28:43] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:28:43] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[20:28:43] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:28:43] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:28:43] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:28:43] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[20:28:43] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[20:28:43] [Server thread/INFO]: View Distance: 10
[20:28:43] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:28:43] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:28:43] [Server thread/INFO]: Item Despawn Rate: 6000
[20:28:43] [Server thread/INFO]: Item Merge Radius: 2.5
[20:28:43] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[20:28:43] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:28:43] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Carrot Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Potato Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Vine Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Kelp Growth Modifier: 100%
[20:28:43] [Server thread/INFO]: Mob Spawn Range: 6
[20:28:43] [Server thread/INFO]: Max TNT Explosions: 100
[20:28:43] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:28:43] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[20:28:43] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:28:43] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:28:43] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:28:43] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[20:28:43] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:47] [Server thread/INFO]: Preparing spawn area: 0%
[20:28:48] [Server thread/INFO]: Preparing spawn area: 1%
[20:28:48] [Server thread/INFO]: Preparing spawn area: 49%
[20:28:56] [Worker-Main-6/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:56] [Worker-Main-6/INFO]: Preparing spawn area: 83%
[20:28:57] [Worker-Main-6/INFO]: Preparing spawn area: 83%
[20:28:57] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:28:58] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:58] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:28:59] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:28:59] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:00] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:00] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:01] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:01] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:02] [Worker-Main-5/INFO]: Preparing spawn area: 84%
[20:29:02] [Worker-Main-5/INFO]: Preparing spawn area: 85%
[20:29:03] [Worker-Main-4/INFO]: Preparing spawn area: 86%
[20:29:03] [Worker-Main-6/INFO]: Preparing spawn area: 88%
[20:29:04] [Server thread/INFO]: Preparing spawn area: 91%
[20:29:04] [Worker-Main-5/INFO]: Preparing spawn area: 93%
[20:29:05] [Worker-Main-6/INFO]: Preparing spawn area: 93%
[20:29:05] [Worker-Main-6/INFO]: Preparing spawn area: 96%
[20:29:06] [Server thread/INFO]: Preparing spawn area: 98%
[20:29:06] [Server thread/INFO]: Time elapsed: 23326 ms
[20:29:06] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[20:29:08] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:08] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:08] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:08] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:08] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:09] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:09] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:10] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:10] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:11] [Worker-Main-6/INFO]: Preparing spawn area: 83%
[20:29:11] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:12] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:12] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:13] [Worker-Main-6/INFO]: Preparing spawn area: 83%
[20:29:13] [Worker-Main-6/INFO]: Preparing spawn area: 83%
[20:29:14] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:14] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:15] [Worker-Main-6/INFO]: Preparing spawn area: 91%
[20:29:15] [Worker-Main-5/INFO]: Preparing spawn area: 91%
[20:29:16] [Worker-Main-4/INFO]: Preparing spawn area: 93%
[20:29:16] [Worker-Main-5/INFO]: Preparing spawn area: 94%
[20:29:17] [Server thread/INFO]: Time elapsed: 10453 ms
[20:29:17] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[20:29:18] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:18] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:18] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:18] [Server thread/INFO]: Preparing spawn area: 0%
[20:29:19] [Worker-Main-5/INFO]: Preparing spawn area: 83%
[20:29:19] [Worker-Main-4/INFO]: Preparing spawn area: 83%
[20:29:20] [Worker-Main-5/INFO]: Preparing spawn area: 88%
[20:29:20] [Server thread/INFO]: Time elapsed: 3268 ms
[20:29:20] [Server thread/INFO]: [BitQuest] Enabling BitQuest v2.0
[20:29:20] [Server thread/INFO]: [startup]BitQuest starting
[20:29:20] [Server thread/INFO]: [warning]ADMIN_UUID env variable is not set.
[20:29:20] [Server thread/INFO]: [startup] sending command gamerule keepInventory on
[20:29:20] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[20:29:20] [Server thread/INFO]: [startup] checking default config file
[20:29:20] [Server thread/INFO]: [startup]Redis host is: redis
[20:29:20] [Server thread/INFO]: [startup]Redis port is: 6379
[20:29:20] [Server thread/INFO]: http://localhost:44555
[20:29:21] [Server thread/WARN]: java.net.SocketTimeoutException: connect timed out
[20:29:21] [Server thread/WARN]: 	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
[20:29:21] [Server thread/WARN]: 	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
[20:29:21] [Server thread/WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[20:29:21] [Server thread/WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[20:29:21] [Server thread/WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[20:29:21] [Server thread/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:609)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
[20:29:21] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
[20:29:21] [Server thread/WARN]: 	at com.bitquest.bitquest.Node.rpcCall(Node.java:43)
[20:29:21] [Server thread/WARN]: 	at com.bitquest.bitquest.Node.getAccountAddress(Node.java:138)
[20:29:21] [Server thread/WARN]: 	at com.bitquest.bitquest.Wallet.address(Wallet.java:21)
[20:29:21] [Server thread/WARN]: 	at com.bitquest.bitquest.BitQuest.onEnable(BitQuest.java:212)
[20:29:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:29:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[20:29:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:29:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[20:29:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[20:29:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435)
[20:29:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218)
[20:29:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
[20:29:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[20:29:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[20:29:21] [Server thread/INFO]: [fatal]Enabling plugin fails. Server is shutting down.
[20:29:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:29:21] [Server thread/INFO]: Done (39.445s)! For help, type "help"
[20:29:21] [Server thread/INFO]: Stopping server
[20:29:21] [Server thread/INFO]: [BitQuest] Disabling BitQuest v2.0
[20:29:22] [Server thread/INFO]: Saving players
[20:29:22] [Server thread/INFO]: Saving worlds
[20:29:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20:29:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[20:29:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[20:29:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:29:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[20:29:32] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:29:32] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[20:29:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:29:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
```

**Comment by PillagerMC** [comment]
Not working on Spigot and PaperMC

**Comment by PillagerMC** [comment]
Is it redis?

**Comment by BitcoinJake09** [comment]
> Is it redis?

It does appear to be a redis issue

**Comment by explodi** [comment]
the server is not able to locate your node and it's trying to connect to: `http://localhost:44555` (the default port of the dogecoin testnet daemon)

**Comment by BitcoinJake09** [comment]
> the server is not able to connect to a node. The defaults is host: localhost and port 44555 (the default port of the dogecoin testnet daemon).

oh, Explodi correct, not redis issue, redis looks to have loaded fine from docker.
yeah PillagerMC you need a Dogecoin node or equivalent codebase fork.

```
[20:29:20] [Server thread/INFO]: [startup]Redis host is: redis
[20:29:20] [Server thread/INFO]: [startup]Redis port is: 6379
[20:29:20] [Server thread/INFO]: http://localhost:44555
[20:29:21] [Server thread/WARN]: java.net.SocketTimeoutException: connect timed out
```

**Comment by explodi** [comment]
The plugin now sends a better error when this happens so it's easier to debug when creating a server.
